Repository dcs4cop/xcube, pull requests merged in 2020-02, with the labels that each got.

#271 xcube server to also serve meta-data
  CHANGES.md
  examples/serve/demo/config.yml
  examples/serve/demo/images/inside-cube/0.jpg
  examples/serve/demo/images/inside-cube/1.jpg
  examples/serve/demo/images/inside-cube/2.jpg
  examples/serve/demo/images/inside-cube/3.jpg
  examples/serve/demo/images/outside-cube/4.jpg
  examples/serve/demo/images/outside-cube/5.jpg
  examples/serve/demo/images/outside-cube/6.jpg
  examples/serve/demo/places/inside-cube-media.geojson
  test/webapi/controllers/test_places.py
  test/webapi/test_context.py
  xcube/cli/serve.py
  xcube/webapi/app.py
  xcube/webapi/context.py
  xcube/webapi/controllers/catalogue.py
  xcube/webapi/controllers/places.py
  xcube/webapi/handlers.py
Labels: DCFS, DCS4COP

#264 Forman 263 access control
  CHANGES.md
  environment.yml
  examples/serve/demo/config.yml
  test/webapi/test_auth.py
  xcube/webapi/auth.py
  xcube/webapi/context.py
  xcube/webapi/controllers/catalogue.py
  xcube/webapi/errors.py
  xcube/webapi/handlers.py
Labels: CyanoAlert

#273 Forman 272 computed vars
  CHANGES.md
  examples/serve/demo/compute_extra_vars.py
  examples/serve/demo/config.yml
  test/core/test_mldataset.py
  test/webapi/helpers.py
  test/webapi/res/test/config-aug.yml
  test/webapi/res/test/config.yml
  test/webapi/res/test/script.py
  test/webapi/test_context.py
  xcube/core/mldataset.py
  xcube/webapi/auth.py
  xcube/webapi/context.py
Labels: CyanoAlert, important, urgent

#276 Forman xxx include dataset attributions
  CHANGES.md
  examples/serve/demo/config.yml
  test/webapi/controllers/test_catalogue.py
  test/webapi/helpers.py
  test/webapi/res/test/config.yml
  xcube/webapi/controllers/catalogue.py
  xcube/webapi/service.py
Labels: CyanoAlert, enhancement, important, urgent

#230 write_cube to s3 bucket
  CHANGES.md
  environment.yml
  test/core/test_dsio.py
  xcube/core/dsio.py
Labels: DCFS
